version: '3'

services:
  db:
    volumes:
      - "./data/mysql:/var/lib/mysql"
    command: "--default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci"
    image: mysql
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
      - "MYSQL_DATABASE=FindRoom"
    ports:
      - "33069:3306"
    networks:
      - findroom-network
  web:
    image: dockerexample
    environment:
      MYSQL_DATABASE: FindRoom
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_HOST: db
    depends_on:
      - db
    restart: always
    networks:
      - findroom-network

networks:
  findroom-network:
    driver: bridge
